### ISSUE TITLE
Error on program start on sway master

### ISSUE THREAD

**Issue by alexarice** [kennylevinsen/wldash#36]
As of yesterday I get the following error when starting wldash:

```
zwlr_layer_surface_v1@14: error 1: width 0 requested without setting left and right anchors
thread 'main' panicked at 'Failed to dispatch all messages.: Os { code: 71, kind: Other, message: "Protocol error" }', src/main.rs:315:21
stack backtrace:
   0:     0x5608970e0c1b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8e44e3bad104136e
   1:     0x56089708a0ed - core::fmt::write::he8cb6d64ed166147
   2:     0x5608970eea56 - std::io::Write::write_fmt::hf25ce96005919ce6
   3:     0x5608970e748a - std::panicking::default_hook::{{closure}}::hf8bcda2c877e2dcc
   4:     0x5608970e705f - std::panicking::rust_panic_with_hook::h7b83b0fe7900eb7a
   5:     0x5608970e6d3a - rust_begin_unwind
   6:     0x560897088d00 - core::panicking::panic_fmt::h61e03e91a1a8868a
   7:     0x560897089e42 - core::result::unwrap_failed::hfb81d2c162de1956
   8:     0x560897139fe4 - wldash::main::h8212739dcc7d5852
   9:     0x5608970e0973 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9597725d379735e1
  10:     0x560897135394 - main
  11:     0x7fab7b1fac7d - __libc_start_main
  12:     0x5608970781aa - _start
  13:                0x0 - <unknown>
fish: “RUST_BACKTRACE=full wldash” terminated by signal SIGABRT (Abort)
```

`sway --version` reports `sway version 1.5-989123a2 (Aug 11 2020, branch 'master')`

Any idea what has caused this issue?

**Comment by alexarice** [comment]
No issue with sway 1.5

**Comment by kennylevinsen** [comment]
Hmm. Works fine here. Please obtain the wayland debug output (`WAYLAND_DEBUG=client wldash`).

**Comment by ja0nz** [comment]
Same problem here on this sway version. I'll wait for a next sway release before investigation.

**Comment by alexarice** [comment]
> Hmm. Works fine here. Please obtain the wayland debug output (`WAYLAND_DEBUG=client wldash`).

Will do this when I find the time to switch back to sway master

**Comment by ja0nz** [comment]
@alexarice Let me do that for you
`$ WAYLAND_DEBUG=client RUST_BACKTRACE=1 wldash`
```
[4168890.829]  -> wl_display@1.get_registry(new id wl_registry@2)
[4168890.863]  -> wl_display@1.sync(new id wl_callback@3)
[4168890.985] wl_display@1.delete_id(3)
[4168891.007] wl_registry@2.global(1, "wl_shm", 1)
[4168891.039] wl_registry@2.global(2, "wl_drm", 2)
[4168891.058] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 3)
[4168891.077] wl_registry@2.global(4, "wl_compositor", 4)
[4168891.094] wl_registry@2.global(5, "wl_subcompositor", 1)
[4168891.113] wl_registry@2.global(6, "wl_data_device_manager", 3)
[4168891.132] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[4168891.151] wl_registry@2.global(8, "gtk_primary_selection_device_manager", 1)
[4168891.169] wl_registry@2.global(9, "zxdg_output_manager_v1", 3)
[4168891.188] wl_registry@2.global(10, "org_kde_kwin_idle", 1)
[4168891.206] wl_registry@2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[4168891.224] wl_registry@2.global(12, "zwlr_layer_shell_v1", 2)
[4168891.242] wl_registry@2.global(13, "xdg_wm_base", 2)
[4168891.261] wl_registry@2.global(14, "zwp_tablet_manager_v2", 1)
[4168891.279] wl_registry@2.global(15, "org_kde_kwin_server_decoration_manager", 1)
[4168891.297] wl_registry@2.global(16, "zxdg_decoration_manager_v1", 1)
[4168891.315] wl_registry@2.global(17, "zwp_relative_pointer_manager_v1", 1)
[4168891.334] wl_registry@2.global(18, "zwp_pointer_constraints_v1", 1)
[4168891.356] wl_registry@2.global(19, "wp_presentation", 1)
[4168891.374] wl_registry@2.global(20, "zwlr_output_manager_v1", 2)
[4168891.393] wl_registry@2.global(21, "zwlr_output_power_manager_v1", 1)
[4168891.413] wl_registry@2.global(22, "zwp_input_method_manager_v2", 1)
[4168891.432] wl_registry@2.global(23, "zwp_text_input_manager_v3", 1)
[4168891.451] wl_registry@2.global(24, "zwlr_foreign_toplevel_manager_v1", 2)
[4168891.470] wl_registry@2.global(25, "zwlr_export_dmabuf_manager_v1", 1)
[4168891.488] wl_registry@2.global(26, "zwlr_screencopy_manager_v1", 3)
[4168891.507] wl_registry@2.global(27, "zwlr_data_control_manager_v1", 2)
[4168891.525] wl_registry@2.global(28, "zwp_primary_selection_device_manager_v1", 1)
[4168891.544] wl_registry@2.global(29, "wp_viewporter", 1)
[4168891.568] wl_registry@2.global(30, "zwp_virtual_keyboard_manager_v1", 1)
[4168891.587] wl_registry@2.global(31, "zwlr_virtual_pointer_manager_v1", 2)
[4168891.606] wl_registry@2.global(32, "zwlr_input_inhibit_manager_v1", 1)
[4168891.625] wl_registry@2.global(33, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[4168891.643] wl_registry@2.global(34, "wl_seat", 7)
[4168891.660] wl_registry@2.global(35, "zwp_pointer_gestures_v1", 1)
[4168891.678] wl_registry@2.global(36, "wl_output", 3)
[4168891.709]  -> wl_registry@2.bind(36, "wl_output", 3, new id [unknown]@4)
[4168891.746] wl_registry@2.global(37, "wl_output", 3)
[4168891.772]  -> wl_registry@2.bind(37, "wl_output", 3, new id [unknown]@5)
[4168891.801] wl_callback@3.done(1221)
[4168891.815]  -> wl_display@1.sync(new id wl_callback@3)
[4168891.918] wl_display@1.delete_id(3)
[4168891.932] wl_output@4.geometry(0, 0, 310, 170, 0, "Unknown", "0x0418", 0)
[4168891.979] wl_output@4.mode(1, 2560, 1440, 60004)
[4168892.007] wl_output@4.scale(2)
[4168892.016] wl_output@4.done()
[4168892.024] wl_output@5.geometry(0, 0, 480, 270, 0, "Goldstar Company Ltd", "LG IPS FULLHD", 0)
[4168892.071] wl_output@5.mode(1, 1920, 1080, 60000)
[4168892.100] wl_output@5.scale(1)
[4168892.111] wl_output@5.done()
[4168892.118] wl_callback@3.done(1221)
[4168892.131]  -> wl_registry@2.bind(4, "wl_compositor", 4, new id [unknown]@3)
[4168892.168]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@6)
[4168892.224]  -> wl_shm@6.create_pool(new id wl_shm_pool@7, fd 19, 128)
[4168892.274]  -> wl_shm@6.create_pool(new id wl_shm_pool@8, fd 21, 128)
[4168892.305]  -> wl_registry@2.bind(34, "wl_seat", 6, new id [unknown]@9)
[4168899.429]  -> wl_seat@9.get_keyboard(new id wl_keyboard@10)
[4168899.487]  -> wl_registry@2.bind(12, "zwlr_layer_shell_v1", 1, new id [unknown]@11)
[4168899.519]  -> wl_display@1.sync(new id wl_callback@12)
[4168900.000] wl_display@1.delete_id(12)
[4168900.033] wl_shm@6.format(0)
[4168900.056] wl_shm@6.format(1)
[4168900.061] wl_shm@6.format(875709016)
[4168900.068] wl_shm@6.format(875708993)
[4168900.073] wl_seat@9.name("seat0")
[4168900.087] wl_seat@9.capabilities(7)
[4168900.097] wl_keyboard@10.keymap(1, fd 19, 63623)
[4168903.111] wl_keyboard@10.repeat_info(25, 600)
[4168903.130] wl_callback@12.done(1223)
[4168903.160]  -> wl_seat@9.get_pointer(new id wl_pointer@12)
[4168903.183]  -> wl_compositor@3.create_surface(new id wl_surface@13)
[4168903.200]  -> zwlr_layer_shell_v1@11.get_layer_surface(new id zwlr_layer_surface_v1@14, wl_surface@13, nil, 3, "")
[4168903.235]  -> zwlr_layer_surface_v1@14.set_keyboard_interactivity(1)
[4168903.247]  -> wl_surface@13.set_buffer_scale(1)
[4168903.259]  -> wl_surface@13.commit()
[4168904.452] wl_display@1.error(zwlr_layer_surface_v1@14, 1, "width 0 requested without setting left and right anchors")
zwlr_layer_surface_v1@14: error 1: width 0 requested without setting left and right anchors
thread 'main' panicked at 'Failed to dispatch all messages.: Os { code: 71, kind: Other, message: "Protocol error" }', src/main.rs:315:21
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: wldash::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: “WAYLAND_DEBUG=client RUST_BACKT…” terminated by signal SIGABRT (Abort)
```

**Comment by kennylevinsen** [comment]
Should be fixed now.
